export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { v4 as uuidv4 } from 'uuid';

export async function POST(request: NextRequest) {
  try {
    const { proposal_id } = await request.json();
    
    console.log('Confirm API called with proposal_id:', proposal_id);
    
    if (!proposal_id) {
      return NextResponse.json(
        { error: 'proposal_id is required' },
        { status: 400 }
      );
    }

    // シンプルなモック提案データ
    const mockProposal = {
      id: proposal_id,
      title: "選択されたタスク",
      slot: "09:00",
      duration_min: 20
    };

    // Generate .ics content
    const eventId = uuidv4();
    const now = new Date();
    const tomorrow = new Date(now);
    tomorrow.setDate(tomorrow.getDate() + 1);
    
    // Parse slot time (HH:MM)
    const [hours, minutes] = mockProposal.slot.split(':').map(Number);
    const startTime = new Date(tomorrow);
    startTime.setHours(hours, minutes, 0, 0);
    
    const endTime = new Date(startTime);
    endTime.setMinutes(endTime.getMinutes() + mockProposal.duration_min);

    const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//InnerVoice//EN
BEGIN:VEVENT
UID:${eventId}@innervoice.app
DTSTART:${startTime.toISOString().replace(/[-:]/g, '').split('.')[0]}Z
DTEND:${endTime.toISOString().replace(/[-:]/g, '').split('.')[0]}Z
SUMMARY:${mockProposal.title}
DESCRIPTION:Generated by InnerVoice (${mockProposal.duration_min}分)
END:VEVENT
END:VCALENDAR`;

    // Calculate minutes back (simplified for MVP)
    const minutesBack = Math.max(mockProposal.duration_min - 5, 0); // Assume 5min saved
    
    console.log('Generated ICS content, minutes back:', minutesBack);

    // データベース保存は一時的にスキップ（エラー回避）
    console.log('Skipping database save for debugging');

    // Create blob URL for download
    const blob = new Blob([icsContent], { type: 'text/calendar' });
    
    return NextResponse.json({
      ics_url: `/api/download/${eventId}`,
      minutes_back: minutesBack,
      success: true,
      debug: 'Database save skipped for debugging'
    });

  } catch (error) {
    console.error('Error in /api/confirm:', error);
    return NextResponse.json(
      { 
        error: 'Failed to confirm proposal',
        details: error.message,
        stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
      },
      { status: 500 }
    );
  }
}